### ISSUE TITLE
Connection failure handled ungracefully

### ISSUE THREAD

**Issue by supernothing** [polyswarm/microengine#5]
If `microengine` cannot connect to `polyswarmd`, a somewhat cryptic error message is reported that doesn't make it obvious what's wrong. This is easy to do when running through [this](https://docs.polyswarm.io/Level-0-scratch-to-eicar/).

Steps to reproduce:
1. Run `docker run -it --net=orchestration_default polyswarm/eicar microengine --polyswarmd-addr polyswarmd:31337 --keyfile docker/keyfile --password password --backend eicar` without first starting `polyswarmd` with `docker-compose`.

Expected result:
An error message saying it couldn't connect, and to check the URL of `polyswarmd`.

Actual result:
```
$ docker run -it --net=orchestration_default polyswarm/eicar microengine --polyswarmd-addr polyswarmd:31337 --keyfile docker/keyfile --password password --backend eicar
INFO:root:Using account: 0x05328f171b8c1463eaFDACCA478D9EE6a1d923F8
Traceback (most recent call last):
  File "/usr/bin/microengine", line 11, in <module>
    load_entry_point('microengine==0.1', 'console_scripts', 'microengine')()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/microengine/__main__.py", line 38, in main
    micro_engine_class(polyswarmd_addr, keyfile, password).run(testing)
  File "/usr/lib/python3.6/site-packages/microengine/__init__.py", line 110, in run
    listen_for_events(self))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/site-packages/microengine/__init__.py", line 421, in listen_for_events
    async with websockets.connect(uri) as ws:
  File "/usr/lib/python3.6/site-packages/websockets/client.py", line 390, in __aenter__
    return (yield from self)
  File "/usr/lib/python3.6/site-packages/websockets/client.py", line 397, in __await__
    transport, protocol = yield from self._creating_connection
  File "/usr/lib/python3.6/asyncio/base_events.py", line 734, in create_connection
    infos = f1.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
```
To fix, just need to catch here.

**Comment by myhndl** [comment]
Addressed or is being tracked in polyswarm-client
